n_samples: 65000
batch_size: 256

device: 1
seed: 0

latent_dim: 10
max_epochs: 1000
lr: 1e-3

log_every_n_steps: 100
plot_every_n_epochs: 50
ckpt_root: "/home/kendra/Code/Learning_Value_Function_Manifold/scripts/model_checkpoints"
